name: ablang-train
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python>=3.8
    - pytorch>=1.9
    - neptune-client
    - pandas
    - pip
    - pip:
      - pytorch-lightning
      - setuptools==59.5.0
  